### ISSUE TITLE
Lipstick color json data scraper

### ISSUE THREAD

**Issue by sonderlau** [rainwomennowatermelon/LipstickFinder-Backend#1]
I didn't find anything about Lipstick Color Scraper mentioned in your project's report.
I would like to know if the code for this part can be shared.
@janejl @Yizhou-Jack

**Comment by janejl** [comment]
@sonderlau oh, the script is in my local repo, I'll push it later today. The data were extracted from DFS hk, and you might be blocked from scraping due to their anti-scraping policy after several loops.

**Comment by sonderlau** [comment]
Did you make the update? I don't see any more commits in this repo.

**Comment by sonderlau** [comment]
@janejl Sorry but it has been 2 days. Did you forget about that?

**Comment by janejl** [comment]
@sonderlau My local environment didn't work after updating big sur and I couldn't tell which one is the scrapper since I used notebook to do the job.

https://github.com/rainwomennowatermelon/LipstickFinder-Backend/blob/b359285bbcd107c2480d6f9c807ec5b7ddbeefa8/Lipstick.ipynb

**Comment by sonderlau** [comment]
Thank you for your updating which I have been waiting for many days.

> My local environment didn't work

That's fine to me. I can code some basic scraper in Python. 
The reason why I requested you to share your code is I didn't figure out how to recognize lipsticks' liquid and more product info from both the brand official website and DFS.cn.
I've checked the DFS website, and I didn't find much information like yours. But I already have some ideas now based on the code you provided and achieved good stage results.
Anyway, thanks for your codes and share, I am really grateful for what you did. Please also tell Yizhou-Jack I'm sorry for disturbing his private time and his personal repository.

All the best.
